# Generated by Django 3.2 on 2024-08-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='FYPF7', max_length=5, verbose_name='Код подтверждения'),
        ),
    ]
