# Generated by Django 3.2 on 2024-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='01WGM', max_length=5, verbose_name='Код подтверждения'),
        ),
    ]
