# Generated by Django 3.2 on 2024-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='CG4B9', max_length=5, verbose_name='Код подтверждения'),
        ),
    ]
