# Generated by Django 3.2 on 2024-08-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='raiting',
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='title',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviews', verbose_name='Отзыв'),
        ),
    ]
