# Generated by Django 3.2 on 2024-08-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240816_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='review',
        ),
    ]
