# Generated by Django 3.2 on 2024-08-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20240817_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to='reviews.reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_review', to='reviews.title'),
        ),
    ]
